site_name: itsmebishowthapa
site_url: https://itsmebishow.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.select

plugins:
  - blog
  - mkdocs-video
  - glightbox:
      auto_caption: true
  - tags:
      tags_file: tags.md

extra:
  mailto: itsmebishowthapa@gmail.com
  tags:
    Compatibility: compat

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

  
nav:
  - Blog:
      - blog/index.md

  - Tools:
      - Intro: "tools/intro.md"
      - cronjobs: "tools/cronjob.md"
      - SSH: "tools/ssh/ssh.md"

      - Terminal:
        - Tmux: "tools/terminal/tmux/tmux.md"
        - Zsh: "tools/terminal/zsh.md"
        - Pass Command Line: "tools/terminal/pass-command-line.md"
      
      - Git:
        - "Intro": "tools/git/intro.md"
        - "Git": "tools/git/git.md"
        - "Gitlab": "tools/git/gitlab.md"
        - "tricks": "tools/git/tricks.md"
        - "resource": "tools/git/resource.md"

      - Github Actions:
        - "Intro": "tools/github-actions/intro.md"
        - "Workflow": "tools/github-actions/workflow.md"

  - Native:
      - Intro: "code/react-native/intro.md"
      - Topic: "code/react-native/topic.md"
      - Websocket: "code/react-native/websocket.md"

  - Career:
      - Developer: "career/developer-plan.md"
      - Roadmap: "career/study-technique.md"
      - Certification: "career/python-certification.md"
      - Tech Stack: "career/tech-stack.md"
      - Interview Question:
        - "Terminology": "career/interviewquestion/terminology.md"
        - "JavaScript": "career/interviewquestion/javascript.md"
        - "React": "career/interviewquestion/react.md"
        - "Django": "career/interviewquestion/django.md"

  - Video:
      - Intro: "video/vid.md"
      - Productivity: "video/productivity.md"
      - Health: "video/health.md"

  - Research:
      - "AI": "research/ai.md"
      - "Micro-Frontend": "research/micro-frontend.md"
      - "Rabbitmq & Celery": "research/rabbitmq-celery.md"
      - "Wordpress": "research/wordpress.md"
      - "prevent default": "research/js-prevent-default.md"
      - "Tips & Tricks": "research/tricks.md"
      - "CSS & Bootstrap": "research/css-bootstrap.md"
      - "Repositories": "research/repositories.md"
      - "Reference": "research/reference.md"

  - More:
      - Introduction: "more/intro.md"
      
      - Mkdocs:
          - "Intro": "more/mkdocs/intro.md"
          - "Basic": "more/mkdocs/01-advanced-mkdocs.md"
          - "Advanced": "more/mkdocs/02-advanced-mkdocs.md"

      - Books:
          - "Tech Books": "more/books/tech-books.md"
          - "Pocker Devops": "more/books/pocket-devops.md"
          - "Jenkins Guide": "more/books/jenkins-guide.md"
          - "Docker yml": "more/books/docker-compose.md"

      - Cryptography:
          - "Intro": "more/cryptography/intro.md"
          - "Steganography": "more/cryptography/steganography.md"

      - Debian: "more/linux/debian.md"
      - Formula: "more/formula.md"