site_name: itsmebishowthapa
site_url: https://itsmebishow.github.io
theme:
  name: material
  logo: assets/logo/career.png
  favicon: assets/logo/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.select

plugins:
  - blog
  - mkdocs-video
  - search
  - glightbox:
      auto_caption: true
  - tags:
      tags_file: tags.md

extra:
  mailto: itsmebishowthapa@gmail.com
  tags:
    Compatibility: compat

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

nav:
  - Blog:
      - blog/index.md

  - Mobile Developer:
      - Intro: "mobiledev/intro.md"
      - React Native:
          - Intro: "mobiledev/react-native/intro.md"
          - Topic: "mobiledev/react-native/topic.md"
          - Websocket: "mobiledev/react-native/websocket.md"

  - Tools:
      - Intro: "tools/intro.md"
      - CronJob: "tools/cronjob.md"
      - SSH: "tools/ssh/ssh.md"

      - Terminal:
          - Tmux: "tools/terminal/tmux/tmux.md"
          - Zsh: "tools/terminal/zsh.md"
          - Pass Command Line: "tools/terminal/pass-command-line.md"

      - Git:
          - "Intro": "tools/git/intro.md"
          - "Git": "tools/git/git.md"
          - "tricks": "tools/git/tricks.md"
          - "resource": "tools/git/resource.md"

      - Gitlab:
          - "Intro": "tools/gitlab/intro.md"

      - Github Actions:
          - "Intro": "tools/github-actions/intro.md"
          - "Workflow": "tools/github-actions/workflow.md"

  - Career:
      - Study Technique: "career/study-technique.md"
      - Formula: "career/formula.md"
      - Roadmap:
          - Intro: "career/roadmap/intro.md"
          - Developer: "career/roadmap/developer-plan.md"
          - Tech Stack: "career/roadmap/tech-stack.md"
      - Certification:
          - Intro: "career/certification/intro.md"
          - React: "career/certification/react.md"
          - Python: "career/certification/python.md"
      - Interview Question:
          - "Terminology": "career/interviewquestion/terminology.md"
          - "JavaScript": "career/interviewquestion/javascript.md"
          - "React": "career/interviewquestion/react.md"
          - "Django": "career/interviewquestion/django.md"

  - Video:
      - Intro: "video/vid.md"
      - Productivity: "video/productivity.md"
      - Health: "video/health.md"

  - Research:
      - "AI": "research/ai.md"
      - "Micro-Frontend": "research/micro-frontend.md"
      - "Rabbitmq & Celery": "research/rabbitmq-celery.md"
      - "Wordpress": "research/wordpress.md"
      - "prevent default": "research/js-prevent-default.md"
      - "Tips & Tricks": "research/tricks.md"
      - "CSS & Bootstrap": "research/css-bootstrap.md"
      - "Repositories": "research/repositories.md"
      - "Reference": "research/reference.md"
